-- KSNM Database for XIDB
-- Category: KSNM
-- Total KSNMs: 20

local M = {}

M.ksnm_list = {
    {
        name = 'Early Bird Catches the Wyrm',
        level = '75',
        orb_required = 'Themis Orb',
        zone = 'Balga\'s Dais',
        max_members = '18',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Wyrm',
                level = 'Unknown',
                job = 'Unknown',
                type = 'Wyrm',
            },
        },
        note = 'The Wyrm has a Regain effect. Often starts the battle with the use of a TP attack. | The Wyrm has MP which can be Aspired. | On the ground, the Wyrm is very similar to Fafnir, except that its Draw In can draw in the entire alliance if someone out of range of its normal attack pulls hate. It has the same TP attacks: | Dragon Breath: Breath Attack which can do lots of damage to anyone in front of the Wyrm. If everyone is standing on its front feet, this will only hit the main target and do relatively little damage. | Hurricane Wing: 30\' AoE Wind damage (~650 before reductions) and blindness (-100 accuracy) for 30 seconds. | Absolute Terror: Single target Terror. | Horrid Roar: Removes one random buff from the target. | Spike Flail: Only used if the target is behind the Wyrm. Extreme 30\' AoE physical damage, absorbed by Utsusemi. | The Wyrm will take flight when it goes below 66% HP and will stay up until it gets down below 33% HP. While in the air, it will not use Dragon Breath, Absolute Terror, Horrid Roar or Spike Flail, but it gains the use of | Flame Blast - 35\' AoE Fire damage (~900 before reductions). | While in the air, its normal attacks will look like a fireball coming from its mouth, and will do Fire damage (~325 per hit before reductions) instead of physical damage. | ~220 total Fire resistance (from gear, Carol and Barspell) is enough to usually reduce its normal attack to ~12 damage, and also dramatically reduce Flame Blast damage. | 329 total Fire resistance from gear, Carol, Barfira, and Shell5 was able to reduce its normal attack in the air to 0 damage. It was also able to nearly nullify its flame blast damage | Magic, Ranged Attacks, Chi Blast, Jump, High Jump, and Avatars can damage it quite well while it is in the air. Melee attacks will not work. | Upon landing, it will use Touchdown. | After landing, the Wyrm\'s evasion, defense, and magic defense will significantly increase. Accuracy food may be needed for melee to hit reliably. | Upon failure orb not reusable have to toss and get another. "There is a crack in the Themis orb. It no longer contains a monster."',
        rewards = {
            {
                group = 'Zero to one of:',
                items = {
                    'HorizonXI specific changes Wyrm Beard',
                },
            },
            {
                group = 'Zero to one of:',
                items = {
                    'Siren\'s Hair (77.5%)',
                },
            },
            {
                group = 'Zero to one of:',
                items = {
                    'Hi-Reraiser (21%)',
                },
            },
            {
                group = 'Zero to one of:',
                items = {
                    'Dragon Heart (52.2%)',
                    'Dragon Meat (34.6%)',
                    'Juggernaut (8.2%)',
                    'Speed Belt (5.9%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Coral Fragment (3.2%)',
                    'Darksteel Ore (7.1%)',
                    'Demon Horn (7.9%)',
                    'Ebony Log (5.6%)',
                    'Gold Ore (7.1%)',
                    'Gold Thread (3.2%)',
                    'Hi-Reraiser (4.8%)',
                    'Mahogany Log (12.7%)',
                    'Mythril Ore (11.1%)',
                    'Petrified Log (18.3%)',
                    'Philosopher\'s Stone (4%)',
                    'Platinum Ore (5.6%)',
                    'Ram Horn (2.4%)',
                    'Raxa (11.9%)',
                    'Reraiser (5.6%)',
                    'Vile Elixir +1 (4%)',
                    'Wyvern Scales (2.4%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Coral Fragment (8.7%)',
                    'Darksteel Ore (8%)',
                    'Demon Horn (5.8%)',
                    'Ebony Log (7.2%)',
                    'Gold Ore (8.7%)',
                    'Gold Thread (1.4%)',
                    'Hi-Reraiser (2.2%)',
                    'Mahogany Log (8%)',
                    'Mythril Ore (3.6%)',
                    'Petrified Log (14.5%)',
                    'Phoenix Feather (0.7%)',
                    'Platinum Ore (5.1%)',
                    'Rainbow Cloth (2.9%)',
                    'Ram Horn (3.6%)',
                    'Raxa (7.2%)',
                    'Reraiser (2.9%)',
                    'Vile Elixir (2.9%)',
                    'Vile Elixir +1 (0.7%)',
                    'Wyvern Scales (2.2%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Libation Abjuration (21.3%)',
                    'Guespiere (18.2%)',
                    'Havoc Scythe (6.5%)',
                    'Leopard Axe (4.3%)',
                    'Nokizaru Shuriken (18.1%)',
                    'Shinsoku (21.7%)',
                    'Somnus Signa (4.3%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Oblation Abjuration (15.9%)',
                    'Bayard\'s Sword (15.1%)',
                    'Dreizack (16.7%)',
                    'Grim Staff (9.5%)',
                    'Grosveneur\'s Bow (9.5%)',
                    'Stylet (5.6%)',
                    'Unsho (34.1%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Beetle Blood (5.8%)',
                    'Damascene Cloth (3.6%)',
                    'Damascus Ingot (7.2%)',
                    'Malboro Fiber (2.2%)',
                    'Philosopher\'s Stone (27.5%)',
                    'Phoenix Feather (19.6%)',
                    'Raxa (22.5%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Mind Potion (9.4%)',
                    'Intelligence Potion (13%)',
                    'Charisma Potion (11.6%)',
                    'Icarus Wing (5.1%)',
                    'Raxa (24.6%)',
                    'Prelatic Pole (24.6%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Hi-Ether +3 (29%)',
                    'Hi-Potion +3 (22.5%)',
                    'Hi-Reraiser (21%)',
                    'Vile Elixir +1 (21.7%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Divine Log (9.4%)',
                    'Lacquer Tree Log (19.6%)',
                    'Petrified Log (57.2%)',
                    'Shining Cloth (4.3%)',
                },
            },
        },
    },
    {
        name = 'Eye of the Storm',
        level = '75',
        orb_required = 'Lachesis Orb',
        zone = 'Chamber of Oracles',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Blizzard Wyvern',
                level = '75-76',
                job = 'Unknown',
                type = 'Wyverns',
            },
            {
                name = 'Lightning Wyvern',
                level = '75-76',
                job = 'Unknown',
                type = 'Wyverns',
            },
        },
        note = '',
        rewards = {
            {
                group = 'All of:',
                items = {
                    'Wyvern Wing',
                    'Wyvern Skin',
                    '24,000 gil',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Woodville\'s Axe (15%)',
                    'Thanatos Baselard (15%)',
                    'Wyvern Perch (20%)',
                    'Balin\'s Sword (30%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Bourdonasse (15%)',
                    'Vile Elixir (15%)',
                    '- class="toau"',
                    'Sword Strap (25%)',
                    '- class="toau"',
                    'Claymore Grip (5%)',
                    '- class="toau"',
                    'Pole Grip (15%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Ziska\'s Crossbow (20%)',
                    'Unji (15%)',
                    'Taillefer\'s Dagger (20%)',
                    'Schiltron Spear (35%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Thunder III (8.5%)',
                    'Thunder III (5%)',
                    'Thunder III (8.5%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Damascus Ingot (8.5%)',
                    'Damascene Cloth (6.5%)',
                    'Malboro Fiber (4.5%)',
                    'Phoenix Feather (10%)',
                    'Philosopher\'s Stone (6.5%)',
                    'Raxa (6.5%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Mythril Ore (5%)',
                    'Darksteel Ore (5%)',
                    'Mythril Ingot (5%)',
                    'Mahogany Log (7.5%)',
                    'Ebony Log (6%)',
                    'Petrified Log (7.5%)',
                    'Gold Ore (5%)',
                    'Platinum Ore (5%)',
                    'Gold Thread (5%)',
                    'Rainbow Cloth (5%)',
                    'Phoenix Feather (2%)',
                    'Coral Fragment (5%)',
                    'Ram Horn (5%)',
                    'Demon Horn (5%)',
                    'Philosopher\'s Stone (5%)',
                    'Raxa (12%)',
                    'Granite (2.5%)',
                    'Reraiser (5%)',
                    'Hi-Reraiser (2.5%)',
                },
            },
        },
    },
    {
        name = 'Horns of War',
        level = '75',
        orb_required = 'Themis Orb',
        zone = 'Horlais Peak',
        max_members = '18',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Chlevnik',
                level = 'Unknown',
                job = 'Unknown',
                type = 'Behemoth',
            },
        },
        note = '',
        rewards = {
            {
                group = 'Unknown Grouping:',
                items = {
                    'Speed Belt (5.9%) HorizonXI specific changes',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Mind Potion (17.2%)',
                    'Intelligence Potion (8%)',
                    'Charisma Potion (10.6%)',
                    'Icarus Wing (17.2%)',
                    'Angel Lyre (23.9%)',
                    'Emerald (10.7%)',
                    'Spinel (4.1%)',
                    'Ruby (5.5%)',
                    'Diamond (2.8%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Behemoth Hide (52.7%)',
                    'Behemoth Horn (42.8%)',
                    'Healing Staff (5.3%)',
                },
            },
            {
                group = 'Zero to one of:',
                items = {
                    'Behemoth Tongue HorizonXI specific changes',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Coral Fragment (12.3%)',
                    'Raxa (0.5%)',
                    'Demon Horn (9.8%)',
                    'Gold Ore (1.8%)',
                    'Mythril Ore (7.1%)',
                    'Vile Elixir (4.4%)',
                    'Ram Horn (1.9%)',
                    'Petrified Log (28%)',
                    'Platinum Ore (0.5%)',
                    'Mahogany Log (4.5%)',
                    'Wyvern Scales (5.8%)',
                    'Granite (3.1%)',
                    'Darksteel Ore (3%)',
                    'Ebony Log (3%)',
                    'Hi-Reraiser (2%)',
                    'Gold Thread (9.6%)',
                    'Rainbow Cloth (1.7%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Demon Horn (8.6%)',
                    'Petrified Log (4.7%)',
                    'Raxa (4.7%)',
                    'Rainbow Cloth (0.7%)',
                    'Hi-Reraiser (9.9%)',
                    'Petrified Log (17.9%)',
                    'Philosopher\'s Stone (11.3%)',
                    'Gold Ore (4.7%)',
                    'Mythril Ore (6%)',
                    'Coral Fragment (4.7%)',
                    'Mahogany Log (6%)',
                    'Wyvern Scales (2%)',
                    'Darksteel Ore (2%)',
                    'Ram Horn (4.7%)',
                    'Ebony Log (7.3%)',
                    'Reraiser (0.7%)',
                    'Platinum Ore (2%)',
                    'Vile Elixir (2%)',
                    'Vile Elixir +1 (0.1%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Libation Abjuration (15.8%)',
                    'Kriegsbeil (26.3%)',
                    'Shinsoku (9.2%)',
                    'Nokizaru Shuriken (7.9%)',
                    'Guespiere (6.6%)',
                    'Purgatory Mace (10.5%)',
                    'Meteor Cesti (23.7%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Oblation Abjuration (16.9%)',
                    'Unsho (1.2%)',
                    'Harlequin\'s Horn (23.5%)',
                    'Dreizack (7.7%)',
                    'Gawain\'s Axe (24.8%)',
                    'Zen Pole (19.5%)',
                    'Bayard\'s Sword (6.4%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Raxa (11.4%)',
                    'Malboro Fiber (5%)',
                    'Philosopher\'s Stone (22%)',
                    'Phoenix Feather (40.4%)',
                    'Damascene Cloth (6.2%)',
                    'Damascus Ingot (4.9%)',
                    'Beetle Blood (10.1%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Behemoth Horn (31.8%)',
                    'Strength Potion (14.7%)',
                    'Dexterity Potion (6.8%)',
                    'Agility Potion (13.4%)',
                    'Vitality Potion (13.4%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Petrified Log (55.6%)',
                    'Lacquer Tree Log (28.9%)',
                    'Shining Cloth (2.5%)',
                    'Divine Log (13%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Hi-Ether +3 (28.9%)',
                    'Hi-Potion +3 (23.7%)',
                    'Hi-Reraiser (19.8%)',
                    'Vile Elixir +1 (27.6%)',
                },
            },
            {
                group = 'width="20%" | One of:',
                items = {
                    'Beastly Shank (0%)',
                },
            },
        },
    },
    {
        name = 'Operation Desert Swarm',
        level = '75',
        orb_required = 'Lachesis Orb',
        zone = 'Waughroon Shrine',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Platoon Scorpion x 6',
                level = '~70',
                job = 'Unknown',
                type = 'Scorpion',
            },
        },
        note = '',
        rewards = {
            {
                group = 'One of:',
                items = {
                    'H.Q. Scorpion Shell (81.3%)',
                    'Venomous Claw (12.3%)',
                    'Serket Ring (5.5%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Expunger (21.6%)',
                    'Heart Snatcher (29.5%)',
                    'Rampager (23.9%)',
                    'Senjuinrikio (23.1%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Anubis\'s Knife (50.4%)',
                    'Adaman Ingot (2.2%)',
                    '- class="toau"',
                    'Claymore Grip (8.6%)',
                    '- class="toau"',
                    'Pole Grip (14.6%)',
                    '- class="toau"',
                    'Sword Strap (2.2%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Hierarch Belt (28.7%)',
                    'Palmerin\'s Shield (21.6%)',
                    'Trainer\'s Gloves (19.8%)',
                    'Warwolf Belt (28.7%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Beetle Blood (7.8%)',
                    'Damascene Cloth (5.6%)',
                    'Damascus Ingot (9.6%)',
                    'Malboro Fiber (5.6%)',
                    'Philosopher\'s Stone (15.7%)',
                    'Phoenix Feather (27.6%)',
                    'Raxa (20.9%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Coral Fragment (5.2%)',
                    'Darksteel Ore (5.6%)',
                    'Demon Horn (4.1%)',
                    'Ebony Log (3.6%)',
                    'Gold Ore (5.2%)',
                    'Gold Thread (2.6%)',
                    'Granite (1.1%)',
                    'Hi-Reraiser (3.7%)',
                    'Mahogany Log (10.1%)',
                    'Mythril Ore (5.2%)',
                    'Petrified Log (11.6%)',
                    'Phoenix Feather (1.5%)',
                    'Philosopher\'s Stone (5.6%)',
                    'Platinum Ore (4.5%)',
                    'Rainbow Cloth (2.2%)',
                    'Ram Horn (6.7%)',
                    'Raxa (11.9%)',
                    'Reraiser (4.5%)',
                    'Vile Elixir (1.9%)',
                    'Vile Elixir +1 (4.1%)',
                    'Wyvern Scales (3.4%)',
                },
            },
        },
    },
    {
        name = 'Royale Ramble',
        level = '75',
        orb_required = 'Lachesis Orb',
        zone = 'Royale Ramble',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'King of Cups',
                level = 'Unknown',
                job = 'White Mage',
                type = 'Cardian',
            },
            {
                name = 'King of Swords',
                level = 'Unknown',
                job = 'Paladin',
                type = 'Cardian',
            },
            {
                name = 'Queen of Cups',
                level = 'Unknown',
                job = 'White Mage',
                type = 'Cardian',
            },
        },
        note = '',
        rewards = {
            {
                group = 'All of:',
                items = {
                    'Orichalcum Ingot (100%)',
                },
            },
            {
                group = 'Zero to one of:',
                items = {
                    '- class=',
                    'Claymore Grip (7%)',
                    '- class=',
                    'Pole Grip (10%)',
                    '- class=',
                    'Sword Strap (28%)',
                    'Trump Crown (52%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Coffinmaker (20%)',
                    'Destroyers (30%)',
                    'Dissector (25%)',
                    'HorizonXI specific changes Perforator (25%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'King of Cups (Card) (25%)',
                    'King of Batons (Card) (35%)',
                    'King of Swords (Card) (25%)',
                    'King of Coins (Card) (25%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Hierarch Belt (20%)',
                    'Palmerin\'s Shield (25%)',
                    'Trainer\'s Gloves (25%)',
                    'Warwolf Belt (30%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Beetle Blood (6%)',
                    'Damascene Cloth (4%)',
                    'Damascus Ingot (9%)',
                    'Malboro Fiber (5%)',
                    'Philosopher\'s Stone (20%)',
                    'Phoenix Feather (30%)',
                    'Raxa (26%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Mythril Ore (5%)',
                    'Darksteel Ore (5%)',
                    'Mahogany Log (8%)',
                    'Ebony Log (7.2%)',
                    'Petrified Log (13%)',
                    'Gold Ore (6%)',
                    'Platinum Ore (3%)',
                    'Gold Thread (6%)',
                    'Rainbow Cloth (3%)',
                    'Malboro Fiber (2%)',
                    'Wyvern Scales (3%)',
                    'Coral Fragment (6%)',
                    'Ram Horn (6%)',
                    'Demon Horn (6%)',
                    'Philosophers Stone (3%)',
                    'Granite (2%)',
                    'Reraiser (4%)',
                    'Hi-Reraiser (3%)',
                    'Vile Elixir (4%)',
                    'Vile Elixir +1 (1%)',
                },
            },
        },
    },
    {
        name = 'The Hills Are Alive',
        level = '75',
        orb_required = 'Themis Orb',
        zone = 'Waughroon Shrine',
        max_members = '18',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Tartaruga Gigante',
                level = 'Unknown',
                job = 'Black Mage/White Mage',
                type = 'Adamantoises',
            },
        },
        note = '',
        rewards = {
            {
                group = 'One of:',
                items = {
                    'Adamantoise Egg (50%) HorizonXI specific changes',
                    'Divine Log (7.9%)',
                    'Lacquer Tree Log (25.7%)',
                    'Petrified Log (33.7%)',
                    'Shining Cloth (14.9%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Adaman Ore (10.7%)',
                    'Darksteel Ore (17.9%)',
                    'Icarus Wing (13.4%)',
                    'Intelligence Potion (15.2%)',
                    'Mind Potion (8%)',
                    'Orichalcum Ore (8%)',
                    'Platinum Ore (10.7%)',
                    'Princely Sword (15.2%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Coral Fragment (13.9%)',
                    'Darksteel Ore (5.9%)',
                    'Demon Horn (5%)',
                    'Ebony Log (10.9%)',
                    'Gold Ore (6.9%)',
                    'Granite (9.9%)',
                    'Hi-Reraiser (7.9%)',
                    'Mahogany Log (12.9%)',
                    'Mythril Ore (10.9%)',
                    'Phoenix Feather (7.9%)',
                    'Petrified Log (16.8%)',
                    'Platinum Ore (12.9%)',
                    'Ram Horn (10.9%)',
                    'Raxa (7.9%)',
                    'Vile Elixir (6.9%)',
                    'Wyvern Scales (7.9%)',
                    'Reraiser (5%)',
                    'Gold Thread (8.9%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Coral Fragment (11.6%)',
                    'Darksteel Ore (8.9%)',
                    'Demon Horn (7.1%)',
                    'Ebony Log (15.2%)',
                    'Gold Ore (10.7%)',
                    'Gold Thread (8.9%)',
                    'Granite (4.5%)',
                    'Hi-Reraiser (7.1%)',
                    'Mahogany Log (10.7%)',
                    'Petrified Log (22.3%)',
                    'Platinum Ore (11.6%)',
                    'Rainbow Cloth (5.4%)',
                    'Ram Horn (5.4%)',
                    'Raxa (7.1%)',
                    'Reraiser (4.5%)',
                    'Vile Elixir (6.3%)',
                    'Wyvern Scales (5.4%)',
                    'Vile Elixir +1 (4.5%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Beetle Blood (10.9%)',
                    'Damascene Cloth (8.9%)',
                    'Damascus Ingot (7.9%)',
                    'Malboro Fiber (9.9%)',
                    'Philosopher\'s Stone (18.8%)',
                    'Phoenix Feather (23.8%)',
                    'Raxa (10.9%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Havoc Scythe (18.8%)',
                    'Kriegsbeil (2.7%)',
                    'Leopard Axe (17%)',
                    'Libation Abjuration (29.5%)',
                    'Meteor Cesti (2.7%)',
                    'Purgatory Mace (7.1%)',
                    'Somnus Signa (19.6%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Gawain\'s Axe (4.5%)',
                    'Grim Staff (25.9%)',
                    'Grosveneur\'s Bow (24.1%)',
                    'Harlequin\'s Horn (13.4%)',
                    'Oblation Abjuration (16.1%)',
                    'Stylet (14.3%)',
                    'Zen Pole (3.6%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Speed Belt (5%) HorizonXI specific changes',
                    'Adaman Chain (44.6%)',
                    'Adamantoise Shell (42%)',
                    'Angel Skin (7.1%)',
                    'Strider Boots (2.6%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Adaman Chain (26.8%)',
                    'Agility Potion (8%)',
                    'Dexterity Potion (14.3%)',
                    'Strength Potion (21.4%)',
                    'Vitality Potion (19.6%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Hi-Ether +3 (29.5%)',
                    'Hi-Potion +3 (25%)',
                    'Hi-Reraiser (19.6%)',
                    'Vile Elixir +1 (21.4%)',
                },
            },
        },
    },
    {
        name = 'Today\'s Horoscope',
        level = '75',
        orb_required = 'Lachesis Orb',
        zone = 'Horlais Peak',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Aries',
                level = 'Unknown',
                job = 'Unknown',
                type = 'Ram',
            },
        },
        note = 'Aries Attacks very quickly similar to 100 fists effect. | Aries uses: Ram special attacks including Severe HP down effect | Uses Stoneskin, Paralyga and Petrabreath | Completely resists Paralyze, Silence, and Slow. | It is immune to Charm and Stun, but susceptible to Sleep, Gravity, Bind, and Blind. | Regens HP at decent rate. "Aries enters a deep sleep" Presumably, gains TP while sleeping also. | Can be taken down with a BLM kite-nuke method.',
        rewards = {
            {
                group = 'All of:',
                items = {
                    '24,000 Gil (100%)',
                },
            },
            {
                group = 'Zero to one of:',
                items = {
                    'Aries Mantle (25%)',
                    'Adaman Ingot (23%)',
                    'Orichalcum Ingot (17.8%)',
                },
            },
            {
                group = 'Zero to one of:',
                items = {
                    'Beetle Blood (4.1%)',
                    'Damascene Cloth (9%)',
                    'Damascus Ingot (2.9%)',
                    'Malboro Fiber (7.6%)',
                    'Philosopher\'s Stone (14.8%)',
                    'Phoenix Feather (23.4%)',
                    'Raxa (23.2%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Gravedigger (22.2%)',
                    'Rampager (24.5%)',
                    'Retributor (23.1%)',
                    'Perforator (30.2%) HorizonXI specific changes',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Hierarch Belt (25%)',
                    'Palmerin\'s Shield (20.6%)',
                    'Trainer\'s Gloves (20.6%)',
                    'Warwolf Belt (33.8%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Rampaging Horn (29.2%)',
                    'Lumbering Horn (26.5%)',
                    '-class="toau"',
                    'Sword Strap (35.4%)',
                    '-class="toau"',
                    'Claymore Grip (8.9%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Mythril Ore (4.1%)',
                    'Darksteel Ore (6.8%)',
                    'Mahogany Log (4.1%)',
                    'Ebony Log (12.1%)',
                    'Petrified Log (7.2%)',
                    'Gold Ore (10.9%)',
                    'Platinum Ore (4.4%)',
                    'Gold Thread (6%)',
                    'Rainbow Cloth (1.4%)',
                    'Malboro Fiber (2%)',
                    'Wyvern Scales (4.4%)',
                    'Coral Fragment (8%)',
                    'Ram Horn (1.4%)',
                    'Demon Horn (6.1%)',
                    'Phoenix Feather (11.1%)',
                    'Raxa (10.5%)',
                    'Reraiser (3.4%)',
                    'Hi-Reraiser (1.4%)',
                    'Vile Elixir +1 (2.7%)',
                },
            },
        },
    },
    {
        name = 'Unknown',
        level = '75',
        orb_required = 'Clotho Orb',
        zone = 'Chamber of Oracles',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Sabotender Campeon x 1',
                level = 'Unknown',
                job = 'White Mage',
                type = 'Sabotender',
            },
        },
        note = 'All have the Sabotender special attacks. | Sabotender Campeon casts Cure V, has Auto-Regen, and runs around regularly inside the BCNM. | Sabotender Amante share hate somewhat strangely with the Campeon. | After Sabotender Campeon finishes running around the BCNM he will immediately fire 1000 Needles | All of the NMs are highly, if not totally immune to sleep.',
        rewards = {
            {
                group = 'One of:',
                items = {
                    'Cactuar Needle (70%)',
                    'Cactus Stems (25%)',
                    'Cactuar Root (5%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Nothing (25%)',
                    'Damascus Ingot (10%)',
                    'Damascene Cloth (15%)',
                    'Malboro Fiber (10%)',
                    'Philosopher\'s Stone (10%)',
                    'Phoenix Feather (5%)',
                    'Raxa (25%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Cactuar Ribbon (25%)',
                    'Capricorn Staff (25%)',
                    'Argent Dagger (25%)',
                    'Balan\'s Sword (25%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Ziska\'s Crossbow (20%)',
                    'Honebami (20%)',
                    'Unji (20%)',
                    'Taillefer\'s Dagger (20%)',
                    'Schiltron Spear (20%)',
                },
            },
            {
                group = 'Unknown Grouping:',
                items = {
                    'Spear Strap (0%)',
                    'Pole Grip (0%)',
                    'Sword Strap (0%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Ram Horn (5%)',
                    'Demon Horn (5%)',
                    'Gold Thread (5%)',
                    'Darksteel Ore (5%)',
                    'Rainbow Cloth (5%)',
                    'Petrified Log (5%)',
                    'Mythril Ore (5%)',
                    'Mahogany Log (5%)',
                    'Ebony Log (5%)',
                    'Vile Elixir (5%)',
                    'Vile Elixir +1 (5%)',
                    'Scroll of Thunder III (5%)',
                    'Scroll of Cure V (5%)',
                    'Coral Fragment (5%)',
                    'Shell IV (5%)',
                    'Phoenix Feather (5%)',
                    'Wyvern Scales (5%)',
                    'Philosopher\'s Stone (5%)',
                    'Granite (5%)',
                    'Raxa (5%)',
                },
            },
        },
    },
    {
        name = 'Unknown',
        level = '75',
        orb_required = 'Clotho Orb',
        zone = 'Qu\'Bia Arena',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Anansi',
                level = 'Unknown',
                job = 'Unknown',
                type = 'Spider',
            },
        },
        note = '',
        rewards = {
            {
                group = 'Zero to One of',
                items = {
                    'Ocean Rope (15%)',
                    'Jungle Rope (15%)',
                    'Steppe Rope (15%)',
                    'Desert Rope (15%)',
                    'Forest Rope (15%)',
                },
            },
            {
                group = 'Zero to One of',
                items = {
                    'Cure V (10%)',
                    'Thunder III (10%)',
                    'Shell IV (10%)',
                    'Light Spirit Pact (10%)',
                },
            },
            {
                group = 'Zero to One of',
                items = {
                    'Damascus Ingot (5%)',
                    'Damascene Cloth (5%)',
                    'Malboro Fiber (5%)',
                    'Philosophers Stone (25%)',
                    'Beetle Blood (5%)',
                    'Raxa (35%)',
                },
            },
            {
                group = 'Zero to One of',
                items = {
                    'Sword Strap (25%)',
                    'Pole Grip (25%)',
                    'Spear Strap (25%)',
                },
            },
            {
                group = 'Zero to One of',
                items = {
                    'Soldier\'s Earring (5%)',
                    'Kampfer Earring (5%)',
                    'Medicine Earring (5%)',
                    'Sorcerer\'s Earring (5%)',
                    'Fencer\'s Earring (5%)',
                    'Rogue\'s Earring (5%)',
                    'Guardian Earring (5%)',
                    'Slayer\'s Earring (5%)',
                    'Tamer\'s Earring (5%)',
                    'Minstrel\'s Earring (5%)',
                    'Tracker\'s Earring (5%)',
                    'Shinobi Earring (5%)',
                    'Drake Earring (5%)',
                },
            },
            {
                group = 'Zero to One of',
                items = {
                    'Mythril Ore (7%)',
                    'Mahogany Log (7%)',
                    'Petrified Log (7%)',
                    'Gold Ore (7%)',
                    'Platinum Ore (7%)',
                    'Gold Thread (7%)',
                    'Rainbow Cloth (7%)',
                    'Phoenix Feather (7%)',
                    'Coral Fragment (7%)',
                    'Ram Horn (7%)',
                    'Demon Horn (7%)',
                    'Vile Elixir +1 (7%)',
                    'Raxa (7%)',
                },
            },
        },
    },
    {
        name = 'Unknown',
        level = 'No restriction',
        orb_required = 'Atropos Orb',
        zone = 'Horlais Peak',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Evil Oscar x 1',
                level = 'Unknown',
                job = 'Unknown',
                type = 'Morbol',
            },
        },
        note = 'Evil Oscar uses Morbol special attacks and \'\'\'Extremely Bad Breath\'\'\' that causes instant death. From experience it appears to be a radial AoE attack, but it only has a range of approximately 10\'. | At certain time intervals, the chat log will display the message "Evil Oscar begins filling his lungs with the foul air around him..."; once this message has been displayed for the third time, Evil Oscar will immediately start to ready \'\'\'Extremely Bad Breath\'\'\' if its target is within range. If its target is not within range, it will wait until it is before readying the attack. | The time between warnings for \'\'\'Extremely Bad Breath\'\'\' shorten as the fight progresses. | It is possible to outrun \'\'\'Extremely Bad Breath\'\'\' before it occurs, as it has a long readying time. However, even if its intended target runs out of range, it can still hit others. | Evil Oscar\'s physical attacks have an added effect of Weight. The effect is extremely potent and will make escape from \'\'\'Extremely Bad Breath\'\'\' almost impossible if you are targeted by it. Utsusemi is highly recommended for anyone at risk of receiving physical blows. | His Impale Tp move does Bind, unlike normal Morbols. | It is susceptible to Gravity and Bind, but will gradually gain resistance to both effects with repeated use. | It is susceptible to DoT spells such as: Dia/Bio, Poison, Elemental Enfeebles, Helixes, and Requiem. | It is immune to Sleep and Stun. | It has about 10,000-12,500 HP.',
        rewards = {
            {
                group = 'All of',
                items = {
                    'Malboro Fiber',
                    'Morbolger Vine HorizonXI specific changes',
                },
            },
            {
                group = 'One of',
                items = {
                    'Adaman Ingot (15.9%)',
                    'Orichalcum Ingot (29%)',
                    'Oscar Scarf (40.6%)',
                },
            },
            {
                group = 'One of',
                items = {
                    'Beetle Blood (8.7%)',
                    'Damascus Ingot (1.4%)',
                    'Damascene Cloth (2.9%)',
                    'Malboro Fiber (4.3%)',
                    'Philosopher\'s Stone (17.4%)',
                    'Phoenix Feather (24.6%)',
                    'Raxa (15.9%)',
                },
            },
            {
                group = 'One of',
                items = {
                    'Cassie Earring (10.1%)',
                    'Malboro Vine (27.5%)<!--',
                    'Claymore Grip (4.3%)',
                    'Pole Grip (20.3%)',
                    'Spear Strap (11.6%)-->',
                },
            },
            {
                group = 'One of',
                items = {
                    'Michishiba (21.7%)',
                    'Morgenstern (14.7%)',
                    'Senjuinrikio (33.3%)',
                    'Thyrsusstab (17.4%)',
                },
            },
            {
                group = 'One of',
                items = {
                    'Evoker\'s Boots (15.9%)',
                    'Ostreger Mitts (21.7%)',
                    'Pineal Hat (14.5%)',
                    'Tracker\'s Kecks (15.9%)',
                },
            },
            {
                group = 'One of',
                items = {
                    'Coral Fragment (10.1%)',
                    'Darksteel Ore (2.9%)',
                    'Demon Horn (2.9%)',
                    'Ebony Log (2.9%)',
                    'Gold Ore (10.1%)',
                    'Gold Thread (2.9%)',
                    'Granite (2.9%)',
                    'Mahogany Log (4.3%)',
                    'Mythril Ore (2.9%)',
                    'Petrified Log (2.8%)',
                    'Platinum Ore (1.4%)',
                    'Rainbow Cloth (5.8%)',
                    'Ram Horn (1.4%)',
                    'Vile Elixir (5.8%)',
                    'Vile Elixir +1 (2.9%)',
                    'Wyvern Scales (7.2%)',
                },
            },
        },
    },
    {
        name = 'Unknown',
        level = '75',
        orb_required = 'Clotho Orb',
        zone = 'Waughroon Shrine',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Osschaar',
                level = 'Unknown',
                job = 'Unknown',
                type = 'Ahriman',
            },
            {
                name = 'Osschaart\'s Avatar',
                level = 'Unknown',
                job = 'Unknown',
                type = 'Avatar',
            },
            {
                name = 'Osschaart\'s Wyvern',
                level = 'Unknown',
                job = 'Unknown',
                type = 'Wyvern',
            },
        },
        note = 'Osschaart has around 18,000-20,000 HP. | Osschaart uses Ahriman special attacks, Draw In, and Charm on party members about every 30 seconds. | Osschaart uses Tier III-aga spells, these vary, watch for which one he is casting, and have someone throw up a bar-spell. | Osschaart always charms the person that traded the Clotho Orb first. | When it uses Charm on a new character, the old one is no longer charmed. | Osschaart is susceptible to Sleep and Lullaby. Will build resistance to Lullaby, shortening sleep time considerably. | Osschaart is only susceptible to Silence through Elemental Seal. | It almost always uses charm immediately after Draw In.',
        rewards = {
            {
                group = 'All of:',
                items = {
                    'Adaman Ingot (100%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Coffinmaker (25%)',
                    'Destroyers (25%)',
                    'Expunger (25%)',
                    'Retributor (25%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Attila\'s Earring (25%)',
                    'Durandal (25%)',
                    'Sorrowful Harp (25%)',
                    'Hoplites Harpe (10%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Ahriman Lens (25%)',
                    'Ahriman Wing (25%)',
                    '- class="toau"',
                    'Pole Grip (5%)',
                    '- class="toau"',
                    'Sword Strap (1.5%)',
                    '- class="toau"',
                    'Spear Strap (25%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Beetle Blood (5%)',
                    'Damascene Cloth (5%)',
                    'Damascus Ingot (5%)',
                    'Malboro Fiber (5%)',
                    'Philosopher\'s Stone (30%)',
                    'Phoenix Feather (30%)',
                    'Raxa (20%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Fuma Sune-Ate (55%)',
                    'Adaman Ingot (20%)',
                    'Orichalcum Ingot (25%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    '- BGCOLOR=#ffdead',
                    'Coral Fragment (5%)',
                    'Darksteel Ore (5%)',
                    'Demon Horn (5%)',
                    'Ebony Log (5%)',
                    'Gold Ore (5%)',
                    'Gold Thread (5%)',
                    'Hi-Reraiser (5%)',
                    'Platinum Ore (5%)',
                    'Mahogany Log (5%)',
                    'Malboro Fiber (5%)',
                    'Mythril Ore (5%)',
                    'Petrified Log (5%)',
                    'Rainbow Cloth (5%)',
                    'Ram Horn (5%)',
                    'Raxa (5%)',
                    'Reraiser (5%)',
                    'Vile Elixir (5%)',
                    'Wyvern Scales (5%)',
                    'Philosopher\'s Stone (5%)',
                },
            },
        },
    },
    {
        name = 'Unknown',
        level = '75',
        orb_required = 'Clotho Orb',
        zone = 'Horlais Peak',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Dragonian Berzerker',
                level = 'Unknown',
                job = 'Warrior',
                type = 'Dragon',
            },
        },
        note = 'Both use Dragon special attacks. | Both are susceptible to: Sleep, Gravity, Bind. | Minstrel can be slept with Lullaby, but each time it is Lullabied the duration is reduced until it resists completely. | Berserker uses: Mighty Strikes (War 2hr), Body Slam (Heavy AOE Damage), Chaos Blade (Cone AOE Curse), Heavy Stomp (Heavy AOE Damage + Paralyze) | Minstrel uses: Soul Voice, Army\'s Paeon V, Battlefield Elegy, Foe Requiem VI, Knight\'s Minne IV, Mage\'s Ballad II, Uncanny Etude, Swift Etude, Horde Lullaby, Chaos Blade (Cone AOE Curse), Thornsong (100~150 damage spikes effect), Voidsong (Large AOE Status negation), Lodesong (AOE Gravity) | Chaos Blade (Cone AOE Curse) effect gets stronger after they use their respective 2-hour. 50% HP/MP reduction pre-2 hour and 75% HP/MP reduction post-2 hour. The range for this ability seems to be 25\'. It is possible to stun this move.',
        rewards = {
            {
                group = 'Zero to One of:',
                items = {
                    'Subduer (22.2%)',
                    'Dissector (30.2%)',
                    'Destroyers (24.5%)',
                    'Heart Snatcher (20.8%)',
                },
            },
            {
                group = 'Zero to Two of:',
                items = {
                    'Dragon Blood (1%)',
                    'Dragon Heart (17.6%)',
                    'Dragon Meat (17.6%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Spear Strap (35.4%)',
                    'Sword Strap (16.5%)',
                    'Pole Grip (8.9%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Minuet Earring (58.6%)',
                    'Adaman Ingot (18.4%)',
                    'Orichalcum Ingot (20.7%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Sorrowful Harp (23.8%)',
                    'Attila\'s Earring (25%)',
                    'Durandal (22.5%)',
                    'Hoplites Harpe (27.5%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Damascene Cloth (9.6%)',
                    'Damascus Ingot (2.7%)',
                    'Philosopher\'s Stone (16.4%)',
                    'Phoenix Feather (26%)',
                    'Malboro Fiber (9.6%)',
                    'Raxa (28.8%)',
                    'Beetle Blood (4.1%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Gold Ore (12.2%)',
                    'Reraiser (5.4%)',
                    'Mythril Ore (4.1%)',
                    'Demon Horn (8.1%)',
                    'Ebony Log (14.9%)',
                    'Wyvern Scales (5.4%)',
                    'Vile Elixir +1 (2.7%)',
                    'Mahogany Log (4.1%)',
                    'Coral Fragment (9.5%)',
                    'Petrified Log (10.8%)',
                    'Phoenix Feather (13.5%)',
                    'Platinum Ore (5.4%)',
                    'Ram Horn (1.4%)',
                    'Rainbow Cloth (1.4%)',
                    'Darksteel Ore (6.8%)',
                    'Hi-Reraiser (13.5%)',
                    'Raxa (0%)',
                },
            },
        },
    },
    {
        name = 'Unknown',
        level = '75',
        orb_required = 'Lachesis Orb',
        zone = 'Qu\'Bia Arena',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Earth Pot',
                level = 'Unknown',
                job = 'Unknown',
                type = 'Magic Pot',
            },
            {
                name = 'Fire Pot',
                level = 'Unknown',
                job = 'Unknown',
                type = 'Magic Pot',
            },
            {
                name = 'Thunder Pot',
                level = 'Unknown',
                job = 'Unknown',
                type = 'Magic Pot',
            },
        },
        note = 'When you attack one of the Pots, the others disappear, leaving you with one Pot to fight. They do not aggro - to magic or otherwise - until attacked. | Each Pot has Chainspell as well as various spells of its element - typically a DoT (eg. Rasp), an enfeebling spell (eg. Slow), an enhancing spell (eg. Enstone), a Tier 4 single target nuke (eg. Stone IV), a Tier 3 AoE spell (eg. Stonega III) and an AM (eg. Quake). | They have approximately 10,000 HP. | They have additional effect Stun to their melee attacks, which will activate occasionally. They use other standard pot moves, such as Mysterious Light, Battery charge etc.',
        rewards = {
            {
                group = 'Zero to One of:',
                items = {
                    'Gold Thread (10%)',
                    'Ram Horn (5%)',
                    'Mahogany Log (5%)',
                    'Ebony Log (10%)',
                    'Demon Horn (5%)',
                    'Rainbow Cloth (10%)',
                    'Philosopher\'s Stone (30%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Mythril Ore (10%)',
                    'Ebony Log (5%)',
                    'Gold Ore (5%)',
                    'Rainbow Cloth (5%)',
                    'Phoenix Feather (30%)',
                    'Philosopher\'s Stone (20%)',
                    'Beetle Blood (5%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Phoenix Feather (10%)',
                    'Raxa (45%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Soldier\'s Earring (5%)',
                    'Kampfer Earring (5%)',
                    'Medicine Earring (5%)',
                    'Sorcerer\'s Earring (5%)',
                    'Fencer\'s Earring (5%)',
                    'Rogue\'s Earring (5%)',
                    'Guardian Earring (5%)',
                    'Slayer\'s Earring (5%)',
                    'Tamer\'s Earring (5%)',
                    'Minstrel\'s Earring (5%)',
                    'Tracker\'s Earring (5%)',
                    'Shinobi Earring (5%)',
                    'Drake Earring',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    '- class="toau"',
                    'Claymore Grip (15%)',
                    'Coral Fragment (15%)',
                    'Phoenix Feather (15%)',
                    '- class="toau"',
                    'Sword Strap (35%)',
                    '- class="toau"',
                    'Pole Grip (20%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Damascus Ingot (5%)',
                    'Damascene Cloth (5%)',
                    'Malboro Fiber (5%)',
                    'Granite (10%)',
                    'Platinum Ore (5%)',
                    'Darksteel Ore (10%)',
                    'Vile Elixir (5%)',
                    'Wyvern Scales (5%)',
                    'Reraiser (5%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Mahogany Log (5%)',
                    'Petrified Log (35%)',
                    'Rainbow Cloth (10%)',
                    'Scroll of Cure V (5%)',
                    'Scroll of Shell IV (25%)',
                    'Scroll of Thunder III (20%)',
                    'Scroll of Raise III (5%)',
                },
            },
        },
    },
    {
        name = 'Unknown',
        level = '75',
        orb_required = 'Atropos Orb',
        zone = 'Qu\'Bia Arena',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Beelzebub x 1',
                level = 'Unknown',
                job = 'White Mage',
                type = 'Bee',
            },
        },
        note = 'All bees have Pollen and Sharp Sting. Beelzebub\'s Pollen can heal for a couple thousand HP. | Beelzebub has Benediction and casts Cure V, Silencega and Paralyga. | Hell Fly can be charmed and slept | Beelzebub is immune to sleep.',
        rewards = {
            {
                group = 'Zero to One of',
                items = {
                    'Ebony Log (15%)',
                    'Phoenix Feather (50%)',
                },
            },
            {
                group = 'Zero to One of',
                items = {
                    'Phoenix Feather (50%)',
                },
            },
            {
                group = 'Zero to One of',
                items = {
                    'Phoenix Feather (50%)',
                    'Hi-Reraiser (15%)',
                },
            },
            {
                group = 'Zero to One of',
                items = {
                    'Philosopher\'s Stone (40%)',
                    'Phoenix Feather (50%)',
                },
            },
            {
                group = 'Zero to One of',
                items = {
                    'Damascus Ingot (1%)',
                    'Damascene Cloth (1%)',
                    'Raxa (40%)',
                    'Beetle Blood (5%)',
                    'Philosopher\'s Stone (25%)',
                    'Malboro Fiber (1%)',
                },
            },
            {
                group = 'Zero to One of',
                items = {
                    'Ocean Sash (15%)',
                    'Jungle Sash (15%)',
                    'Steppe Sash (15%)',
                    'Desert Sash (15%)',
                    'Forest Sash (15%)',
                },
            },
            {
                group = 'Zero to One of',
                items = {
                    'Mythril Ore (15%)',
                    'Adaman Ore (1%)',
                    'Darksteel Ore (5%)',
                    'Platinum Ore (10%)',
                    'Granite (5%)',
                },
            },
            {
                group = 'Zero to One of',
                items = {
                    'Gold Thread (10%)',
                    'Petrified Log (15%)',
                    'Mahogany Log (10%)',
                    'Ram Horn (20%)',
                    'Coral Fragment (10%)',
                    'Demon Horn (10%)',
                },
            },
            {
                group = 'Zero to One of',
                items = {
                    'Staff Strap (5%)',
                    'Claymore Grip (5%)',
                    'Pole Grip (30%)',
                    'Spear Strap (15%)',
                    'Scroll of Cure V (1%)',
                    'Scroll of Thunder III (1%)',
                    'Scroll of Shell IV (1%)',
                    'Light Spirit Pact (13%)',
                },
            },
            {
                group = 'Zero to Two of',
                items = {
                    'Guardian Earring (5%)',
                    'Kampfer Earring (5%)',
                    'Conjurer\'s Earring (5%)',
                    'Shinobi Earring (5%)',
                    'Tracker\'s Earring (5%)',
                    'Sorcerer\'s Earring (5%)',
                    'Soldier\'s Earring (5%)',
                    'Tamer\'s Earring (5%)',
                    'Medicine Earring (5%)',
                    'Drake Earring (5%)',
                    'Fencer\'s Earring (5%)',
                    'Minstrel\'s Earring (5%)',
                    'Rogue\'s Earring (5%)',
                    'Ronin Earring (5%)',
                    'Slayer\'s Earring (5%)',
                },
            },
        },
    },
    {
        name = 'Unknown',
        level = '75',
        orb_required = 'Atropos Orb',
        zone = 'Balga\'s Dais',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Giant Moa x 2',
                level = 'Unknown',
                job = 'Unknown',
                type = 'Cockatrice',
            },
        },
        note = '',
        rewards = {
            {
                group = 'All of:',
                items = {
                    'Cockatrice Skin x2',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Dodo Skin',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Adaman Ingot (25%)',
                    'Orichalcum Ingot (35%)',
                    'Absorbing Shield (35%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Expunger (25%)',
                    'Morgenstern (25%)',
                    'Heart Snatcher (25%)',
                    'Gravedigger (25%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Ostreger Mitts (25%)',
                    'Pineal Hat (25%)',
                    'Evokers Boots (25%)',
                    'Tracker\'s Kecks (25%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Damascus Ingot (5%)',
                    'Damascene Cloth (5%)',
                    'Phoenix Feather (30%)',
                    'Philosopher\'s Stone (35%)',
                    'Beetle Blood (5%)',
                    'Raxa (20%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Mythril Ore (6%)',
                    'Darksteel Ore (6%)',
                    'Mahogany Log (6%)',
                    'Ebony Log (6%)',
                    'Petrified Log (6%)',
                    'Gold Ore (6%)',
                    'Platinum Ore (6%)',
                    'Gold Ore (6%)',
                    'Rainbow Cloth (11%)',
                    'Wyvern Scales (6%)',
                    'Coral Fragment (6%)',
                    'Ram Horn (6%)',
                    'Demon Horn (11%)',
                    'Hi-Reraiser (6%)',
                    'Vile Elixir (6%)',
                },
            },
        },
    },
    {
        name = 'Unknown',
        level = '75',
        orb_required = 'Cloud Evoker',
        zone = 'Riverne - Site A01',
        max_members = '18',
        time_limit = '60 minutes',
        mobs = {
            {
                name = 'Ouryu',
                level = '85',
                job = 'Paladin',
                type = 'Wyrm',
            },
        },
        note = 'Take the Cloud Evoker into Riverne - Site #A01, and trade it to the green Spatial Displacement at I-9. This allows up to a full alliance to enter the BCNM through the displacement, which takes them into a non-capped battlefield. | You may enter as long as you have access to Monarch Linn (CoP Mission 2-5) | This battlefield is not instanced, so only one alliance may fight this BCNM at a time. | Only Ouryu must be defeated to win this BCNM. | Ouryu has approximately 50,000 HP. | Ouryu is susceptible to: Sleep, Lullaby, Silence, Gravity, Paralyze, Blind. | Ouryu lands for two minutes, then flies for 90 seconds. The Mistmelt item works on him in this fight, just as it does in the mission. | Ouryu\'s offensive abilities include: | Wyrm special attacks. | Draw In. | Invincible. | \'\'\'Absolute Terror\'\'\' (AoE Terror). | \'\'\'Ochre Blast\'\'\'. | \'\'\'Touchdown\'\'\'. | \'\'\'Bai Wing\'\'\' (~250 AoE damage, plus gives Slow effect to all hit by it. Overwrites Haste). | \'\'\'Geotic Breath\'\'\' (Cone-shaped earth elemental damage). | \'\'\'Horrid Roar\'\'\' (All buffs removed, including food). | Stonega III. | Break/Breakga. | Ouryu\'s defensive abilities include: | Stoneskin. | Elementals (one Water, one Earth) will spawn inside the BCNM area. They build resistance to Sleep, and will respawn quickly if killed. | The four summoned Ziryu use: Worm special attacks, Stonega III, Quake. | Ziryu are susceptible to: Sleep, Silence, Gravity, Bind, Charm, Lullaby, Elegy.',
        rewards = {
            {
                group = 'All of:',
                items = {
                    '3 x Kunwu Ore (100%)',
                    'Monarch\'s Orb (100%)',
                    'Tutelary (100%)',
                    'Wyrm Horn (100%)',
                },
            },
            {
                group = 'Zero to one of:',
                items = {
                    'Dragon Heart (20%)',
                    'Damascene Cloth (20%)',
                    'Imanotsurugi (60%)',
                },
            },
            {
                group = 'Zero to one of',
                items = {
                    'Adaman Ingot (9%)',
                    'Behemoth Hide (5%)',
                    'Beetle Blood (19%)',
                    'Damascene Cloth (14%)',
                    'Damascus Ingot (1%)',
                    'Divine Log (9.5%)',
                    'Malboro Fiber (18.5%)',
                    'Siren\'s Hair (15%)',
                },
            },
            {
                group = 'Zero to one of:',
                items = {
                    'Dragon Blood (60%)',
                    'Dragon Talon (25%)',
                    'Oxblood (15%)',
                },
            },
            {
                group = 'Zero to one of:',
                items = {
                    'Dragon Blood (25%)',
                    'Dragon Meat (60%)',
                    'Dragon Talon (15%)',
                },
            },
        },
    },
    {
        name = 'Unknown',
        level = '75',
        orb_required = 'Atropos Orb',
        zone = 'Waughroon Shrine',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Titanis Dax',
                level = 'Unknown',
                job = 'Bard',
                type = 'Roc',
            },
            {
                name = 'Titanis Max',
                level = 'Unknown',
                job = 'Bard',
                type = 'Roc',
            },
        },
        note = 'All four use Greater Bird and Soul Voice special attacks. | When one is killed, the remaining ones are made more powerful. After two were killed, the remaining two both began to hit much faster (seemed to have NO delay), harder, and took less damage. Nin tanks not recommended. | All are susceptible to Sleep, Lullaby, and Bind. Resisted sleep (except with ES) after two of the birds were killed. | Can use 2 hour more than once. | Builds resistance to sleep quickly.',
        rewards = {
            {
                group = 'One of:',
                items = {
                    'Coffinmaker (33.3%)',
                    'Dissector (17.4%)',
                    'Gravedigger (17.4%)',
                    'Michishiba (21.7%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Titanis Earring (40.6%)',
                    'Adaman Ingot (15.9%)',
                    'Orichalcum Ingot (29%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Evoker\'s Boots (15.9%)',
                    'Ostreger Mitts (21.7%)',
                    'Pineal Hat (14.5%)',
                    'Tracker\'s Kecks (15.9%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Giant Bird Plume (27.5%)',
                    'Damascus Ingot (27.5%)',
                    '- class="toau"',
                    'Pole Grip (20.3%)',
                    '- class="toau"',
                    'Spear Strap (11.6%)',
                    '- class="toau"',
                    'Claymore Grip (14.5%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Beetle Blood (8.7%)',
                    'Damascene Cloth (2.9%)',
                    'Damascus Ingot (1.4%)',
                    'Philosopher\'s Stone (17.4%)',
                    'Phoenix Feather (24.6%)',
                    'Raxa (15.9%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Coral Fragment (10.1%)',
                    'Darksteel Ore (2.9%)',
                    'Demon Horn (2.9%)',
                    'Ebony Log (2.9%)',
                    'Gold Ingot (10.1%)',
                    'Gold Thread (2.9%)',
                    'Malboro Fiber (7.2%)',
                    'Petrified Log (5.8%)',
                    'Platinum Ore (1.4%)',
                    'Rainbow Cloth (5.8%)',
                    'Ram Horn (1.4%)',
                    'Raxa (15.9%)',
                    'Mythril Ore (2.9%)',
                },
            },
        },
    },
    {
        name = 'Unknown',
        level = '75',
        orb_required = 'Clotho Orb',
        zone = 'Balga\'s Dais',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Gilagoge Tlugvi',
                level = 'Unknown',
                job = 'White Mage',
                type = 'Treant',
            },
            {
                name = 'Ulagohvsdi Tlugvi',
                level = 'Unknown',
                job = 'Ninja',
                type = 'Treant',
            },
        },
        note = 'All use Treant special attacks. | They do not link when one is pulled. | When one uses it\'s 2 Hour ability, the others wake, in the order of: Spring, Summer, Autumn, Winter. | For reference, Gilagoge is the Spring Treant, Goga the Summer Treant, Ulagohvsdi the Autumn Treant, Gola the Winter Treant. | All are susceptible to Bind, Sleep and Gravity, are extremely resistant to Lullaby, and immune to Charm. Resistance to bind, sleep, and gravity builds fast with repeated castings. | Gilagoge Tlugv uses only "Entangle" (cone Bind effect), Additional Effect: Dispel, and uses Benediction. | Goga Tlugvi uses only "Leafstorm" (AoE 2 shadow images or damage 600-900), Additional Effect: Stun, and uses 100 Fists. | Ulagohvsdi Tlugvi uses only "Pinecone Bomb (ranged single-target 1 shadow image or damage + sleep), Additional Effect: Paralyze, and uses Mijin Gakure. | Gola Tlugvi uses only "Drill Branch" (cone 2 shadow images or damage + blind), Additional Effect: Absorb TP, and uses Blood Weapon.',
        rewards = {
            {
                group = 'Zero to One of:',
                items = {
                    'Durandal (25%)',
                    'Sorrowful Harp (25%)',
                    'Attila\'s Earring (25%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Rampager (20%)',
                    'Morgenstern (20%)',
                    'Subduer (20%)',
                    'Expunger (20%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Root Sabots (33.3%)',
                    'Adaman Ingot (33.3%)',
                    'Orichalcum Ingot (33.3%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Lacquer Tree Log (5%)',
                    'Divine Log (65%)',
                    '- class="toau"',
                    'Spear Strap (10%)',
                    '- class="toau"',
                    'Sword Strap (10%)',
                    '- class="toau"',
                    'Pole Grip (10%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Damascus Ingot (5%)',
                    'Damascene Cloth (5%)',
                    'Beetle Blood (15%)',
                    'Philosopher\'s Stone (10%)',
                    'Raxa (35%)',
                    'Phoenix Feather (30%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Gold Ore (6.6%)',
                    'Platinum Ore (6.6%)',
                    'Darksteel Ore (6.6%)',
                    'Rainbow Cloth (6.6%)',
                    'Ram Horn (6.6%)',
                    'Demon Horn (6.6%)',
                    'Ebony Log (6.6%)',
                    'Petrified Log (6.6%)',
                    'Vile Elixir (6.6%)',
                    'Coral Fragment (6.6%)',
                    'Mahogany Log (6.6%)',
                    'Mythril Ore (6.6%)',
                    'Raxa (6.6%)',
                    'Wyvern Scales (6.6%)',
                },
            },
        },
    },
    {
        name = 'Unknown',
        level = '75',
        orb_required = 'Atropos Orb',
        zone = 'Chamber of Oracles',
        max_members = '6',
        time_limit = '30 minutes',
        mobs = {
            {
                name = 'Purson x 1',
                level = 'Unknown',
                job = 'Unknown',
                type = 'Manticore',
            },
        },
        note = '',
        rewards = {
            {
                group = 'All of',
                items = {
                    'Manticore Hide',
                    'Manticore Hair',
                },
            },
            {
                group = 'One of',
                items = {
                    'Beetle Blood (20%)',
                    'Wyvern Perch (20%)',
                    'Honebami (20%)',
                    'Argent Dagger (20%)',
                    'Thanatos Baselard (20%)',
                },
            },
            {
                group = 'One of',
                items = {
                    'Vile Elixir (35%)',
                    'Vile Elixir +1 (10%)',
                    'Cure V (10%)',
                    '- class="toau"',
                    'Pole Grip (25%)',
                    '- class="toau"',
                    'Spear Strap (10%)',
                    '- class="toau"',
                    'Claymore Grip (10%)',
                },
            },
            {
                group = 'One of',
                items = {
                    'Shell IV (25%)',
                    'Capricorn Staff (15%)',
                    'Woodville\'s Axe (15%)',
                    'King Maker (15%)',
                    'Gawain\'s Axe (15%)',
                    'Balan\'s Sword (15%)',
                },
            },
            {
                group = 'Zero to one of',
                items = {
                    'Damascus Ingot (10%)',
                    'Damascene Cloth (5%)',
                    'Malboro Fiber (5%)',
                    'Philosophers Stone (5%)',
                    'Raxa (10%)',
                },
            },
            {
                group = 'One of',
                items = {
                    'Darksteel Ore (5%)',
                    'Adaman Ore (5%)',
                    'Mahogany Log (10%)%',
                    'Petrified Log (10%)',
                    'Platinum Ore (5%)',
                    'Orichalcum Ore (5%)',
                    'Gold Ingot (2.5%)',
                    'Platinum Ingot (5%)',
                    'Rainbow Cloth (2.5%)',
                    'Phoenix Feather (10%)',
                    'Raxa (10%)',
                    'Reraiser (10%)',
                    'Hi-Reraiser (5%)',
                    'Thunder III (15%)',
                },
            },
        },
    },
    {
        name = 'Unknown',
        level = '75',
        orb_required = 'Monarch\'s Orb',
        zone = 'Riverne - Site B01',
        max_members = '18',
        time_limit = '60 minutes',
        mobs = {
            {
                name = 'Jormungand',
                level = 'Unknown',
                job = 'Dark Knight',
                type = 'Wyrm',
            },
            {
                name = 'Vrtra',
                level = 'Unknown',
                job = 'Beastmaster',
                type = 'Wyrm',
            },
            {
                name = 'Pey x2',
                level = 'Unknown',
                job = 'Warrior',
                type = 'Skeleton',
            },
            {
                name = 'Airi x2',
                level = 'Unknown',
                job = 'Black Mage',
                type = 'Ghost',
            },
        },
        note = 'To enter this fight, one Monarch\'s Orb is to be traded to the green Unstable Displacement on the west side of (E-7). This will allow all other members to select the fight. This is the same battlefield used to fight Bahamut in Storms of Fate. | :\'\'(\'\'\'Note:\'\'\' In addition to one member trading an Orb, \'\'all\'\' Alliance members must have the Whisper of the Wyrmking Key Item. It is necessary to complete the final cutscenes of Storms of Fate before attempting to enter this fight.)\'\' | You will enter the battlefield facing a much stronger version of Bahamut than the one in Storms of Fate. | He has approximately 25000 HP | His Auto Regen is mostly insignificant, but he uses Cure V many times throughout the fight. | He is susceptible to Threnody and Elegy. He is susceptible to Stun, but builds up resistance quickly. He has ~60% resistance to Dispel and Finale. | He casts the same spells as in Storms of Fate, and uses the same TP attacks plus two new ones: | \'\'\'Horrible Roar:\'\'\' Very large AoE (25\'?) dispels 4 effects, including food. | \'\'\'Impulsion:\'\'\' AoE ~500 damage plus Petrify, Blind and Knockback. | As in Storms of Fate, after each 10% HP he loses, Bahamut uses a "flare" attack that hits a very wide (180 degree?) cone. | He talks in /say a few seconds before each flare. | At 90%, 80%, and 70%, he uses \'\'\'Megaflare\'\'\' (~850 fire damage). | "Children of Vana\'diel, what do you think to accomplish by fighting for your lives?" | "You know your efforts are futile, yet still you resist..." | "Atone for your sins against the mothercrystal if you desire to live!" | At 60%, 50%, 40%, 30%, and 20%, he uses \'\'\'Gigaflare\'\'\' (~1200 fire damage). | "I will break your body and sear it to ash, scattered by the wind--never again will you return to the earth of Vana\'diel!" | At 10%, he starts to spam \'\'\'Teraflare\'\'\' (~1800 fire damage). | "Your unity has given you great power, and brought forth hope. However, in the great passage of time, even hope great enough to avert the apocalypse is forgotten. Such is the way of mortals. We can choose to end it all here instead. Your hope will be judged by the raging fires of the Wyrmking!" | Magic Damage Taken and Magic Defense Bonus gear and Fire resistance can reduce flare damage. | At 80%, 60%, 40% and 20% HP, Bahamut summons a weaker version of one of the four Chains of Promathia Wyrms, a different one each time but in random order. | He talks in /say a few seconds before each summon. | "Winged brothers and sisters, hear my call!" | "All those who traverse the endless sea of clouds! All those who bear the shadowless sun as they cross the skies!" | "Come join me in the shedding of divine blood!" | Tiamat and Jormungand have ~6500 HP; Ouryu has ~6000 HP; Vrtra has ~5500 HP. | Vrtra can use Charm multiple times with the same TP, and summons undead like he does in King Ranperre\'s Tomb. | Ouryu is reported to summon Ziryu. Water Elementals and Earth Elementals also appear on the battlefield when Ouryu is summoned, which do not automatically disappear when Ouryu is defeated. | All Wyrms have high magic resistance and defense; unresisted Thunder IV does ~350-550, unresisted Ancient Magic II does ~550-750, and they usually resist by at least half if Threnody is not on. | The last Wyrm will despawn if Bahamut is defeated first. | All enemies in this battle appear to be very highly resistant to all versions of Sleep. Elemental Seal does not appear to make a difference. (Lullaby has not yet been tested, but similar results are expected.)',
        rewards = {
            {
                group = 'One of:',
                items = {
                    'Bahamut\'s Staff (23.1%)',
                    'Dragon Staff (76.9%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Cashmere Cloth (57.6%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Cashmere Thread (59.3%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Wyrm Horn (74.6%)',
                },
            },
            {
                group = 'One of:',
                items = {
                    'Bahamut\'s Mask (31.8%)',
                    'Bahamut\'s Zaghnal (26.8%)',
                    'Bahamut\'s Hose (41.4%)',
                },
            },
            {
                group = 'Zero to All of: (86.4% chance)',
                items = {
                    'Divine Log',
                    'Sirens Hair',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Kunwu Iron (71.2%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Kunwu Ore (67.8%)',
                },
            },
            {
                group = 'Zero to One of',
                items = {
                    'Molybdenum Ore (86.4%)',
                },
            },
            {
                group = 'Zero to One of:',
                items = {
                    'Molybdenum Ore (76.3%)',
                },
            },
        },
    },
}

return M
